#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Generate FastDDS XML configs from .env IP addresses
#
# Reads JETSON_IP, RPI_IP, RPI4_IP, and WS_IP from .env (or environment) and
# writes config/fastdds_{jetson,rpi,rpi4,ws}.xml.
#
# IMPORTANT — Multi-participant unicast discovery:
#   Each ROS 2 node process creates its own DDS Participant.  In unicast-only
#   networks (multicast blocked), FastDDS probes well-known metatraffic ports
#   for a limited range of participant IDs (default: 4).  The Jetson runs 6-8
#   nodes and the RPi 5 runs 5-7 nodes — exceeding this default.  Participants
#   at higher IDs would be invisible to remote devices.
#
#   This script generates explicit port entries in the initialPeersList for
#   each device, covering participant IDs 0 through MAX_PEERS-1.  The DDS
#   well-known unicast metatraffic port formula is:
#     port = 7400 + 250 * DOMAIN_ID + 10 + 2 * PARTICIPANT_ID
#
#   If you change ROS_DOMAIN_ID, re-run this script to recalculate ports.
#
# IMPORTANT — UDP socket buffer sizes:
#   The generated XML requests sendSocketBufferSize=1MB / listenSocketBufferSize=4MB.
#   Linux kernels typically cap UDP buffers at ~212 KB by default.  If the OS
#   refuses the requested size, FastDDS silently falls back to the kernel default,
#   causing packet drops under heavy LiDAR traffic across the network.
#   Run this on ALL SBCs (Jetson, Pi 5, Pi 4b) before first launch:
#
#     sudo sysctl -w net.core.rmem_max=4194304
#     sudo sysctl -w net.core.rmem_default=4194304
#     sudo sysctl -w net.core.wmem_max=1048576
#     sudo sysctl -w net.core.wmem_default=1048576
#
#   To persist across reboots, add those lines to /etc/sysctl.conf and run:
#     sudo sysctl -p
#
# Usage:
#   bash scripts/generate_fastdds_configs.sh          # uses .env in repo root
#   ROS_DOMAIN_ID=42 bash scripts/generate_fastdds_configs.sh
#   JETSON_IP=10.0.0.2 WS_IP=10.0.0.1 RPI_IP=10.0.0.3 bash scripts/generate_fastdds_configs.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$REPO_ROOT/config"

# Load .env if present
if [ -f "$REPO_ROOT/.env" ]; then
    set -a; source "$REPO_ROOT/.env"; set +a
fi

JETSON_IP="${JETSON_IP:-172.23.23.20}"
RPI_IP="${RPI_IP:-172.23.23.51}"
RPI4_IP="${RPI4_IP:-172.23.23.52}"
WS_IP="${WS_IP:-172.23.23.10}"
DOMAIN_ID="${ROS_DOMAIN_ID:-42}"

# Max participants to probe per device (covers current + future nodes).
# More entries = more SPDP probes at startup (harmless UDP packets).
JETSON_MAX_PEERS=10   # brain, admin, action, stt, yolo, rsp, slam, rf2o, ...
RPI_MAX_PEERS=8       # lidar, imu, imu_bridge, imu_tf, lidar_tf, tts, display, ...
RPI4_MAX_PEERS=2      # mecanum_driver (+ headroom)
WS_MAX_PEERS=3        # whatsapp_listener (+ headroom)

mkdir -p "$CONFIG_DIR"

# ── Helper: generate initialPeersList locator entries ──────────────────────
# Generates one <locator> per participant ID with explicit metatraffic port.
# Args: $1=ip  $2=comment  $3=max_participants
gen_peer_entries() {
    local ip="$1"
    local comment="$2"
    local max_pid="$3"
    local base_port=$((7400 + 250 * DOMAIN_ID + 10))

    echo "                        <!-- ${comment} (participant IDs 0-$((max_pid - 1))) -->"
    for ((pid=0; pid<max_pid; pid++)); do
        local port=$((base_port + 2 * pid))
        cat <<PEER
                        <locator>
                            <udpv4>
                                <address>${ip}</address>
                                <port>${port}</port>
                            </udpv4>
                        </locator>
PEER
    done
}

# ── Build the shared initialPeersList (same for all devices) ───────────────
build_all_peers() {
    gen_peer_entries "$WS_IP"     "Workstation (WhatsApp relay / dev)"  "$WS_MAX_PEERS"
    gen_peer_entries "$JETSON_IP" "Jetson Orin Nano (AI / vision)"      "$JETSON_MAX_PEERS"
    gen_peer_entries "$RPI_IP"    "Raspberry Pi 5 (sensors + audio)"    "$RPI_MAX_PEERS"
    gen_peer_entries "$RPI4_IP"   "Raspberry Pi 4b (motor drivers)"     "$RPI4_MAX_PEERS"
}

ALL_PEERS="$(build_all_peers)"

# ── Helper: generate a FastDDS XML profile ──────────────────────────────────
# Args: $1=output_file  $2=profile_name  $3=device_description
#        $4=self_ip  $5=participant_id  $6=node_list  $7=usage_cmd
generate_profile() {
    local output="$1"
    local profile_name="$2"
    local description="$3"
    local self_ip="$4"
    local participant_id="$5"
    local node_list="$6"
    local usage_cmd="$7"

    cat > "$output" << XMLEOF
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  Auto-generated by scripts/generate_fastdds_configs.sh — do not edit by hand.
  To change IPs, edit .env and re-run: bash scripts/generate_fastdds_configs.sh

  Fast DDS profile for the ${description}.
  Runs: ${node_list}
  Device IP: ${self_ip}
  participantID: ${participant_id}
  ROS_DOMAIN_ID: ${DOMAIN_ID}

  NOTE: Multiple nodes on the same device share this profile.  FastDDS 2.x
  auto-increments the participant ID when the computed port is already bound,
  so co-located nodes will NOT crash.  The explicit ID seeds predictable
  well-known ports for unicast discovery across the 4-device mesh.

  MULTI-PARTICIPANT DISCOVERY: The initialPeersList includes explicit
  metatraffic unicast ports for each device's expected participant range.
  Without these, FastDDS only probes the first 4 participant IDs per peer
  address (default max_initial_peers_range=4).  The Jetson runs 6-8 nodes
  as separate processes — participants at ID 5+ would be invisible to
  remote devices, causing silent topic delivery failures (e.g. /robot_speech
  from brain_node never reaching tts_node on the RPi 5).

  UDP BUFFER SIZES: This profile requests 1 MB send / 4 MB receive buffers.
  Linux defaults cap these at ~212 KB — if the OS refuses, FastDDS silently
  falls back, causing packet drops on /scan under load.  On each SBC, run:
    sudo sysctl -w net.core.rmem_max=4194304
    sudo sysctl -w net.core.wmem_max=1048576
  Persist via /etc/sysctl.conf.  See scripts/generate_fastdds_configs.sh.

  If you change ROS_DOMAIN_ID, re-run the generation script — ports are
  computed from the domain ID using the DDS well-known port formula:
    port = 7400 + 250 * DOMAIN_ID + 10 + 2 * PARTICIPANT_ID

  Usage:
    export FASTRTPS_DEFAULT_PROFILES_FILE=/path/to/$(basename "$output")
    ${usage_cmd}
-->
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <profiles>
        <participant profile_name="${profile_name}" is_default_profile="true">
            <rtps>
                <participantID>${participant_id}</participantID>

                <builtin>
                    <discovery_config>
                        <discoveryProtocol>SIMPLE</discoveryProtocol>

                        <simpleEDP>
                            <PUBWRITER_SUBREADER>true</PUBWRITER_SUBREADER>
                            <PUBREADER_SUBWRITER>true</PUBREADER_SUBWRITER>
                        </simpleEDP>
                        <leaseDuration>
                            <sec>20</sec>
                        </leaseDuration>
                        <initialAnnouncements>
                            <count>5</count>
                            <period>
                                <sec>1</sec>
                            </period>
                        </initialAnnouncements>
                    </discovery_config>

                    <metatrafficUnicastLocatorList>
                        <locator>
                            <udpv4>
                                <address>${self_ip}</address>
                            </udpv4>
                        </locator>
                    </metatrafficUnicastLocatorList>

                    <initialPeersList>
${ALL_PEERS}
                    </initialPeersList>
                </builtin>

                <defaultUnicastLocatorList>
                    <locator>
                        <udpv4>
                            <address>${self_ip}</address>
                        </udpv4>
                    </locator>
                </defaultUnicastLocatorList>

                <sendSocketBufferSize>1048576</sendSocketBufferSize>
                <listenSocketBufferSize>4194304</listenSocketBufferSize>
                <useBuiltinTransports>true</useBuiltinTransports>
            </rtps>
        </participant>
    </profiles>
</dds>
XMLEOF

    echo "  Generated: $output  (IP=$self_ip, domain=$DOMAIN_ID)"
}

echo "==> Generating FastDDS configs from .env IPs"
echo "    JETSON_IP=$JETSON_IP  WS_IP=$WS_IP  RPI_IP=$RPI_IP  RPI4_IP=$RPI4_IP"
echo "    ROS_DOMAIN_ID=$DOMAIN_ID"
echo ""

generate_profile \
    "$CONFIG_DIR/fastdds_jetson.xml" \
    "aisha_jetson" \
    "Jetson Orin Nano (AI/vision nodes)" \
    "$JETSON_IP" \
    "1" \
    "brain_node, admin_node, action_node, stt_node, yolov8, rsp, slam, rf2o" \
    "ros2 launch aisha_integration jetson_launch.py"

generate_profile \
    "$CONFIG_DIR/fastdds_rpi.xml" \
    "aisha_rpi" \
    "Raspberry Pi 5 (sensors + audio I/O)" \
    "$RPI_IP" \
    "0" \
    "ldlidar, bno055_imu, imu_bridge, tts_node, llm_display" \
    "ros2 launch aisha_integration rpi_launch.py"

generate_profile \
    "$CONFIG_DIR/fastdds_rpi4.xml" \
    "aisha_rpi4" \
    "Raspberry Pi 4b (motor drivers)" \
    "$RPI4_IP" \
    "3" \
    "mecanum_driver_node" \
    "ros2 launch mecanum_driver pi4_motor_launch.py"

generate_profile \
    "$CONFIG_DIR/fastdds_ws.xml" \
    "aisha_ws" \
    "Workstation (WhatsApp relay / dev)" \
    "$WS_IP" \
    "2" \
    "whatsapp_listener (production) or all nodes (dev_mode)" \
    "ros2 launch aisha_integration ws_launch.py"

echo ""
echo "==> Done. Commit the updated config/*.xml files if IPs or domain ID changed."
